Documentation:
  Enabled: false

AllCops:
  RunRailsCops: true
  Include:
    - Gemfile
    - tasks/*
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - config/**/*
    - bin/**/*
    - db/migrate/20140925235651_devise_create_users.rb
