language: ruby
rvm:
- 1.8.7
- 1.9.2
- 1.9.3
- jruby-18mode
- jruby-19mode
- rbx
deploy:
  provider: heroku
  app: derek-portfolio
  api_key:
    secure: oTUNyLuaakwxhb02NHNYyvgUP7Ee+boQtbWgQ8CV4YBrxA/+oDVOUDwUtJOPZLLfsms5QNHzKEgiiO2JF3VUsOViGRuksqre/H17ZA8juz4s+HpyipX9lxoLs0u7uo03v5pXHHlwQJbYEdgX/+drPUYeh4FZuh8XENVXT99OqN0=
