# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a0be651989b3c9730f265652b4c469bdda51612a40fbcda6c558c7ae818ac848c99793e737080c85125e09423e806fe0273f48ce8ab31e8ab8e2f0a931ab5b6

test:
  secret_key_base: be31801d280627bc05627c1d9175bbd3fb1a9462eb7a87c5f24a50c706555f3d758e8433858be723a5a41bae8f83d83962c9bdce1075803b61603fd605019389

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
